### ISSUE TITLE
[1.18.1] Can't enter any of the worlds

### ISSUE THREAD

**Issue by recon88** [kwpugh/mining_Dimensions#25]
I've added the latest version of Mining Dims to a Fabric Modpack (Benchmark II) and I'm unable to enter any of the dims on my server.
It doesn't even generate the dims if you walk into the portals.
No errors/warnings in console/logs.
Checked level.dat, no entries for the new dims.
Checked config, all dims are enabled.
Removed and added a freshly downloaded copy of the mod again.
Tried different locations/biomes/heights.
Here's a list of all mods + versions: https://pastebin.com/yXuN0M5F

It works in Singleplayer.

Is there anything else I can check?

Edit:
The teleporter devices are throwing exceptions on use. Probably because the dims don't exist?

```
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_3218.method_27983()" because "destWorld" is null
        at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.22) ~[?:?]
        at com.kwpugh.mining_dims.util.TeleporterUtil.movePlayer(TeleporterUtil.java:90) ~[MiningDimensions_Fabric-1.18.1-1.3.0.jar:?]
        at com.kwpugh.mining_dims.items.CavingTeleporter.use(CavingTeleporter.java:33) ~[MiningDimensions_Fabric-1.18.1-1.3.0.jar:?]
        at net.minecraft.item.ItemStack.use(ItemStack:252) ~[?:?]
        at net.minecraft.server.network.ServerPlayerInteractionManager.interactItem(ServerPlayerInteractionManager:282) ~[?:?]
        at net.minecraft.server.network.ServerPlayNetworkHandler.onPlayerInteractItem(ServerPlayNetworkHandler:1093) ~[?:?]
        at net.minecraft.network.packet.c2s.play.PlayerInteractItemC2SPacket.apply(PlayerInteractItemC2SPacket:25) ~[?:?]
        at net.minecraft.network.packet.c2s.play.PlayerInteractItemC2SPacket.apply(PlayerInteractItemC2SPacket:7) ~[?:?]
        at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:21) ~[?:?]
        at net.minecraft.server.ServerTask.run(ServerTask:18) ~[?:?]
        at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:151) ~[?:?]
        at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:780) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:162) ~[server-intermediary.jar:?]
        at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:125) ~[?:?]
        at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer:762) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runTask(MinecraftServer:756) ~[server-intermediary.jar:?]
        at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:134) ~[?:?]
        at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer:741) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:688) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:270) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by kwpugh** [comment]
are the portals enabled in the config

oh, you did that.

**Comment by recon88** [comment]
> Checked config, all dims are enabled.

That's already in my statement above ;)

**Comment by kwpugh** [comment]
No idea what that could be.  Must be another mod that is blocking reading and running of the datapack that creates the dimensions.

**Comment by recon88** [comment]
Seems to be the exact same issue as described here: 
https://github.com/Glitchfiend/TerraBlender/issues/38

Closing as doesn't seem to been an issue with Mining Dimensions. Thanks for looking into.
