### ISSUE TITLE
[1.17.1] Low TPS when play Single

### ISSUE THREAD

**Issue by manaheti1** [kwpugh/mining_Dimensions#8]
I Installed various mods without following any mod pack, they just work together.
But when I installed your mod, my game when from this
![image](https://user-images.githubusercontent.com/65333593/131964578-a561efa8-e768-4530-89e3-b0bccb9b0fe3.png)
to this
![image](https://user-images.githubusercontent.com/65333593/131965142-b0a7bced-6f22-44ab-966e-d0bbeb0b381b.png)
If you want more info about my mods then:
Better End, Better Nether, William Wyther Overhauled Overworld mod and its addon except for Primordial Shore
and some  Structure-Add-Mods . The rest are more recipe mod, client mod I don't think these will cause conflict.

**Comment by kwpugh** [comment]
hmm, this mod is a data pack of dimensions,  there is  no  content that  gets ticked.  Were you  even in one of the dimensions when you took the measurement?

**Comment by manaheti1** [comment]
No I took measure in Overworld, I have never got in a Dimession. Also this TPS drop sometime doesn't happen immediately It may happended right after I create the world or after 5-10 minutes of playing. And after I removed your mod I can't re-enter my old world.

**Comment by kwpugh** [comment]
The lag is odd, since the mod is essentially a data pack mod, so if you aren't in the dimension, the mod is doing nothing.

The removal problem showed up recently, still trying to figure out what is causing that.

**Comment by manaheti1** [comment]
I check the log and It said:

[10:25:14] [Server thread/INFO]: [STDOUT]: Negative index in crash report handler (21/22)
[10:25:14] [Server thread/WARN]: Exception loading entity: 
net.minecraft.class_148: Loading entity NBT
	at net.minecraft.class_1297.method_5651(class_1297.java:1776) ~[intermediary-Fabric%201.17.1.jar:?]
	at net.minecraft.class_1299.method_17839(class_1299.java:485) ~[intermediary-Fabric%201.17.1.jar:?]
	at net.minecraft.class_156.method_17974(class_156.java:448) ~[intermediary-Fabric%201.17.1.jar:?]
	at net.minecraft.class_1299.method_5892(class_1299.java:484) ~[intermediary-Fabric%201.17.1.jar:?]
	at net.minecraft.class_1299.method_17848(class_1299.java:577) ~[intermediary-Fabric%201.17.1.jar:?]
	at net.minecraft.class_1299.method_17842(class_1299.java:528) ~[intermediary-Fabric%201.17.1.jar:?]
	at net.minecraft.class_4482.method_21855(class_4482.java:209) ~[intermediary-Fabric%201.17.1.jar:?]
	at net.minecraft.class_4482.method_21858(class_4482.java:290) ~[intermediary-Fabric%201.17.1.jar:?]
	at net.minecraft.class_4482.method_31656(class_4482.java:299) ~[intermediary-Fabric%201.17.1.jar:?]
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:886) ~[intermediary-Fabric%201.17.1.jar:?]
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:941) ~[intermediary-Fabric%201.17.1.jar:?]
	at net.minecraft.class_1937.method_18471(class_1937.java:474) ~[intermediary-Fabric%201.17.1.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:422) ~[intermediary-Fabric%201.17.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:891) ~[intermediary-Fabric%201.17.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831) ~[intermediary-Fabric%201.17.1.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:96) ~[intermediary-Fabric%201.17.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[intermediary-Fabric%201.17.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-Fabric%201.17.1.jar:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NoSuchMethodError: 'void net.minecraft.class_4466.method_29512(net.minecraft.class_3218, net.minecraft.class_2487)'
	at net.minecraft.class_4466.handler$ccg000$worldCheckAngerFromTag(class_4466.java:804) ~[intermediary-Fabric%201.17.1.jar:?]
	at net.minecraft.class_4466.method_5749(class_4466.java:265) ~[intermediary-Fabric%201.17.1.jar:?]
	at net.minecraft.class_1297.method_5651(class_1297.java:1767) ~[intermediary-Fabric%201.17.1.jar:?]
	... 18 more

repeatly when the TPS dropped.

**Comment by kwpugh** [comment]
I do not believe this is a result  of the mining dims mods since it is simple datapacck mod.  I could not replicate this either.
